events {
  worker_connections 1024;
}

http {
  server {
    listen 80;

    location /api/auth {
      proxy_pass http://core:3001;
    }

    location /api/users {
      proxy_pass http://core:3001;
    }

    location /api/projects {
      proxy_pass http://core:3001;
    }

    location /api/search {
      proxy_pass http://core:3001;
    }

    location /api/messages {
      proxy_pass http://messaging:3002;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }

    location /api/match {
      proxy_pass http://match:3003;
    }
  }
}
